version = 1
SPDX-PackageName = "crypto-communications-assurance"
SPDX-PackageSupplier = "Organization: itdojp"
SPDX-PackageDownloadLocation = "https://github.com/itdojp/crypto-communications-assurance"

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 itdojp contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["integrations/ae-framework/pins/c5da6115638fdbfeebbc458b39fa6916db66afb0/schema/*.json"]
precedence = "override"
SPDX-FileCopyrightText = "ae-framework contributors"
SPDX-License-Identifier = "Apache-2.0"
